### ISSUE TITLE
Local installer service on edge device

### ISSUE THREAD

**Issue by zero88** [NubeIO/iot-engine#129]
Local installer service on edge device:

- [x] Register endpoints to `:edge:module:gateway`
- [x] Endpoints handler in `:dashboard:module:installer` in local mode
- [x] Config to switch local and cluster mode in `:dashboard:module:installer`
- [x] Open dockerized port for `:dashboard:module:gateway`

Recommend using `event message service`.

**Refers**
#130
NubeIO/bonescript-dashboard#81
