### ISSUE TITLE
Improve timeout config for EventBus

### ISSUE THREAD

**Issue by zero88** [NubeIO/iot-engine#135]
Current default delivery event message by `eventbus` is `30s`.
It is short time in some case for example: install remote service from `Nexus`, etc.
Must provide config for `DeliveryOptions` in `EventController`

**Definition of Done**
- [x] Add `DeliveryOption` as attribute of `EventController`
- [x] Add `DeliveryOption` in configuration under `__eventbus__`
- [x] Singleton `EventController` for each `vertx` by using `SharedData`
- [x] Able to override `DeliveryOption` in each method of `EventController`
