### ISSUE TITLE
BACNet/GPIO integrate with Edge gateway

### ISSUE THREAD

**Issue by zero88** [NubeIO/iot-engine#155]
**Description**

It is data workflow
1. Cloud to Edge:
```
Ditto cloud -- --> NodeRed -- --> Edge Gateway |-- --> edge api
                                               |-- --> bacnet
```

2. Edge to Cloud:
```
edge api |-- --> Edge Gateway |-- --> Edge dataPoint -- --> local database
bacnet   |                    |-- --> NodeRed    |-- --> Ditto cloud
                                                 |-- -->  Postgres cloud
```

- **Note**
  - `Edge dashboard` will be backed by `Edge Gateway`, not by `Edge Api` anymore

**Task**
- [x] Integrate `GPIO` `Edge Api` with Edge Gateway
- [ ] Integrate `BACNet` with Edge Gateway
- [ ] Docker for `bios` local include `edge api`, `edge dashboard`, `edge gateway`, `edge installer local`, `edge datapoint`

## example work flow
```BACnet point/history Example
Example workflow of getting a BACnet device and making a writable point over http and storing a history 
This example talking about doing all this work from the edge-dashboard.

Step 1 Adding a BACnet device
Login to the dashboard and add a BACnet network and set the required network settings.
Select the required device and add the required points. (These points would be available over HTTP rest  once added)
Setup the history settings(Set to 15min inveal as per original bs-api setting)
Setup a BACnet polling time for how often we as the BACnet device for its latest value

Step 2  Commanding the new BACnet point from node-red
Now from node-red the BACnet should be available to node-red over HTTP as a virtual point. So i should be able to send a HTTP update to write a new value @1-16 ```
