### ISSUE TITLE
Build initial event bus API

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/iot-engine#93]
- [x] get devices
- [x] get device info
- [x] get device points
- [x] get device point info
